// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorFMS.Data.BlazorFMS;

public partial class Sucursal
{
    public int SucursalId { get; set; }

    public string Nombre { get; set; }

    public string Ubicacion { get; set; }

    public virtual ICollection<Colaboradores> Colaborador { get; set; } = new List<Colaboradores>();
}