// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorFMS.Data.BlazorFMS;

public partial class SucursalDetalles
{
    public int SucursalDetalleId { get; set; }

    public int? SucursalId { get; set; }

    public int? ColaboradorId { get; set; }

    public decimal? DistanciaKilometros { get; set; }

    public virtual Colaboradores Colaborador { get; set; }

    public virtual Sucursales Sucursal { get; set; }
}