// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorFMS.Data.BlazorFMS;

public partial class Transportistas
{
    public int TransportistaId { get; set; }

    public string Nombre { get; set; }

    public decimal TarifaPorKilometro { get; set; }

    public string UserName { get; set; }

    public virtual ICollection<Viajes> Viaje { get; set; } = new List<Viajes>();
}